### ISSUE TITLE
Latest version won't compile nor build

### ISSUE THREAD

**Issue by gabrielstuff** [WilixLead/iohook#14]
The previous version was clonable and installable without any issue.
Now while trying to clone the repo and install I've got the following errors : 

```
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN prefer global node-gyp@3.6.0 should be installed with -g
npm WARN prefer global node-ninja@1.0.2 should be installed with -g

> iohook@0.1.5 install /Users/gabrielstuff/Sources/node/soixante/playground/test-module/iohook
> node install.js

/Users/gabrielstuff/Sources/node/soixante/playground/test-module/iohook/install.js:87
    throw new Error('Can\'t resolve main package.json file');
    ^

Error: Can't resolve main package.json file
    at optionsFromPackage (/Users/gabrielstuff/Sources/node/soixante/playground/test-module/iohook/install.js:87:11)
    at optionsFromPackage (/Users/gabrielstuff/Sources/node/soixante/playground/test-module/iohook/install.js:100:12)
    at optionsFromPackage (/Users/gabrielstuff/Sources/node/soixante/playground/test-module/iohook/install.js:100:12)
    at optionsFromPackage (/Users/gabrielstuff/Sources/node/soixante/playground/test-module/iohook/install.js:100:12)
    at optionsFromPackage (/Users/gabrielstuff/Sources/node/soixante/playground/test-module/iohook/install.js:100:12)
    at Object.<anonymous> (/Users/gabrielstuff/Sources/node/soixante/playground/test-module/iohook/install.js:104:17)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)

npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/gabrielstuff/.nvm/versions/node/v7.4.0/bin/node" "/Users/gabrielstuff/.nvm/versions/node/v7.4.0/bin/npm" "install"
```

more here: https://gist.github.com/a793a06de913edc6ff725f0b84488149

**Comment by WilixLead** [comment]
Yes. Right. I forget add catch for unexisted package.json.
At this moment, you can just add package.json file to your project. Should work

**Comment by gabrielstuff** [comment]
I try that

**Comment by WilixLead** [comment]
Hm. Okay. I try to fix all today asap.

PS. Also, you can try add some parameters to package.json like in [readme.md](https://github.com/WilixLead/iohook#electron-users-optional). It should help you run module now.

**Comment by vespakoen** [comment]
Also, check out this line: https://github.com/WilixLead/iohook/blob/master/install.js#L135
It's getting the ABI from the version number.
This is incorrect, it should not do any lookup there, simply pass along the second part of the string, basically turning the current:

```diff
4c4
<   let version = parts[1];
---
>   let abi = parts[1];
12d11
<           let abi = support.abis[runtime][version];
```

In the install.js file

**Comment by vespakoen** [comment]
Also the example in the readme should remove the "v" prefix from the targets, e.g. change:

```json
  "targets": [
    "node-v51"
    "electron-v53"
  ]
```

into

```json
  "targets": [
    "node-51"
    "electron-53"
  ]
```
