### ISSUE TITLE
the example app can't find the module

### ISSUE THREAD

**Issue by PedroEsperanca** [WilixLead/iohook#17]
```
2017-04-28 21:48:47 ⌚  Pedros-MacBook-Pro in ~/Documents/rants/bg-key-app/iohook/electron-example
± |master U:2 ✗| → npm start

> iohook-electron-example@1.0.0 start /Users/pedroesperanca/Documents/rants/bg-key-app/iohook/electron-example
> electron ./

Loading native binary: /Users/pedroesperanca/Documents/rants/bg-key-app/iohook/electron-example/node_modules/ioHook/builds/electron-v53-darwin-x64/build/Release/iohook.n
ode
App threw an error during load
Error: Cannot find module '/Users/pedroesperanca/Documents/rants/bg-key-app/iohook/electron-example/node_modules/ioHook/builds/electron-v53-darwin-x64/build/Release/ioho
ok.node'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/Users/pedroesperanca/Documents/rants/bg-key-app/iohook/electron-example/node_modules/electron/dist/Electron.app/Contents/Resour
ces/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/pedroesperanca/Documents/rants/bg-key-app/iohook/electron-example/node_modules/ioHook/index.js:16:21)
    at Object.<anonymous> (/Users/pedroesperanca/Documents/rants/bg-key-app/iohook/electron-example/node_modules/ioHook/index.js:110:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
```

**Comment by PedroEsperanca** [comment]
got it too work by changing the iohook config on package.json to:
```
  "iohook": {
    "targets": [
      "node-48",
      "electron-53"
    ]
  }
```
basically removing:
```
    "platforms": [
      "win32",
      "darwin",
      "linux"
    ],
    "arches": [
      "x64",
      "ia32"
    ]
```
