### ISSUE TITLE
Can't install on Linux x64

### ISSUE THREAD

**Issue by dzek69** [WilixLead/iohook#27]
I tried installing the library (yarn, npm - no difference), ended up with:
```
Prebuild for current platform (iohook-v0.1.9-node-v57-linux-x64) not found!
Try to compile for your platform:
# cd node_modules/iohook;
# npm run compile
```
Ok, no big deal.

First issue: the command is `npm run build`, according to package.json

Having all dependencies installed I still got into trouble, because of:

Second issue: `cmake-js` have to be globally installed to be able to do that.

Installed that, but got into:

Third issue: Cannot compile, logs:
```
dzek@dzek-Mint17 ~/Projects/dzekcamp/node_modules/iohook $ npm run build

> iohook@0.1.9 build /home/dzek/Projects/dzekcamp/node_modules/iohook
> cmake-js compile

info TOOL Using Unix Makefiles generator.
info TOOL Using c++11 compiler standard.
info CMD CONFIGURE
WARN invalid config loglevel="notice"
info RUN cmake "/home/dzek/Projects/dzekcamp/node_modules/iohook" --no-warn-unused-cli -G"Unix Makefiles" -DCMAKE_JS_VERSION="3.5.0" -DCMAKE_BUILD_TYPE="Release" -DCMAKE_LIBRARY_OUTPUT_DIRECTORY="/home/dzek/Projects/dzekcamp/node_modules/iohook/build/Release" -DCMAKE_JS_INC="/home/dzek/.cmake-js/node-x64/v8.4.0/include/node;/home/dzek/Projects/dzekcamp/node_modules/nan" -DNODE_RUNTIME="node" -DNODE_RUNTIMEVERSION="8.4.0" -DNODE_ARCH="x64" -DCMAKE_CXX_FLAGS="-std=c++11"
Not searching for unused variables given on the command line.
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
You have called ADD_LIBRARY for library uiohook without any source files. This typically indicates a problem with your CMakeLists.txt file
-- Configuring done
CMake Error: Cannot determine link language for target "uiohook".
CMake Error: CMake can not determine linker language for target: uiohook
-- Generating done
-- Build files have been written to: /home/dzek/Projects/dzekcamp/node_modules/iohook/build
info REP Build has been failed, trying to do a full rebuild.
info CMD CLEAN
info RUN cmake -E remove_directory "/home/dzek/Projects/dzekcamp/node_modules/iohook/build"
info CMD CONFIGURE
info RUN cmake "/home/dzek/Projects/dzekcamp/node_modules/iohook" --no-warn-unused-cli -G"Unix Makefiles" -DCMAKE_JS_VERSION="3.5.0" -DCMAKE_BUILD_TYPE="Release" -DCMAKE_LIBRARY_OUTPUT_DIRECTORY="/home/dzek/Projects/dzekcamp/node_modules/iohook/build/Release" -DCMAKE_JS_INC="/home/dzek/.cmake-js/node-x64/v8.4.0/include/node;/home/dzek/Projects/dzekcamp/node_modules/nan" -DNODE_RUNTIME="node" -DNODE_RUNTIMEVERSION="8.4.0" -DNODE_ARCH="x64" -DCMAKE_CXX_FLAGS="-std=c++11"
Not searching for unused variables given on the command line.
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
You have called ADD_LIBRARY for library uiohook without any source files. This typically indicates a problem with your CMakeLists.txt file
-- Configuring done
CMake Error: Cannot determine link language for target "uiohook".
CMake Error: CMake can not determine linker language for target: uiohook
-- Generating done
-- Build files have been written to: /home/dzek/Projects/dzekcamp/node_modules/iohook/build
ERR! OMG Process terminated: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! iohook@0.1.9 build: `cmake-js compile`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the iohook@0.1.9 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/dzek/.npm/_logs/2017-08-26T16_48_41_366Z-debug.log
dzek@dzek-Mint17 ~/Projects/dzekcamp/node_modules/iohook $ cat /home/dzek/.npm/_logs/2017-08-26T16_48_41_366Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@5.3.0
3 info using node@v8.4.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle iohook@0.1.9~prebuild: iohook@0.1.9
6 info lifecycle iohook@0.1.9~build: iohook@0.1.9
7 verbose lifecycle iohook@0.1.9~build: unsafe-perm in lifecycle true
8 verbose lifecycle iohook@0.1.9~build: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/dzek/Projects/dzekcamp/node_modules/iohook/node_modules/.bin:/home/dzek/Projects/dzekcamp/node_modules/.bin:/home/dzek/bin:/home/dzek/.local/bin:/home/dzek/bin:/home/dzek/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin
9 verbose lifecycle iohook@0.1.9~build: CWD: /home/dzek/Projects/dzekcamp/node_modules/iohook
10 silly lifecycle iohook@0.1.9~build: Args: [ '-c', 'cmake-js compile' ]
11 silly lifecycle iohook@0.1.9~build: Returned: code: 1  signal: null
12 info lifecycle iohook@0.1.9~build: Failed to exec build script
13 verbose stack Error: iohook@0.1.9 build: `cmake-js compile`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:289:16)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at EventEmitter.emit (events.js:213:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at ChildProcess.emit (events.js:213:7)
13 verbose stack     at maybeClose (internal/child_process.js:927:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
14 verbose pkgid iohook@0.1.9
15 verbose cwd /home/dzek/Projects/dzekcamp/node_modules/iohook
16 verbose Linux 4.10.0-30-generic
17 verbose argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
18 verbose node v8.4.0
19 verbose npm  v5.3.0
20 error code ELIFECYCLE
21 error errno 1
22 error iohook@0.1.9 build: `cmake-js compile`
22 error Exit status 1
23 error Failed at the iohook@0.1.9 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

I'd appreciate any help to get this running

**Comment by gavinmcdermott** [comment]
@dzek69 - any luck getting this running?

**Comment by dzek69** [comment]
Nope, I've used another library

**Comment by Tom1827** [comment]
@dzek69 which library did you use, please?  I need to capture keyup events in node...

**Comment by dzek69** [comment]
Can't remember. That another lib had some issues too so I gave up. Sorry I can't help you.

**Comment by WilixLead** [comment]
You can try new install new version with supported 57 abi version. I close it at this moment
