### ISSUE TITLE
I can't install it on manjaro linux

### ISSUE THREAD

**Issue by danieldaeschle** [WilixLead/iohook#84]
## Expected Behavior
It should install

## Current Behavior
It doesn't install

## Possible Solution
Don't know. Just fix it.

## Steps to Reproduce (for bugs)
`npm install --save iohook` with npm 6.0.0 and manjaro linux

## Your Environment
npm 6.0.0
nodejs 10.0.0
manjaro linux newest version

Error:

```
[daniel@daniel-pc amazon-music-linux]$ npm install --save iohook
npm WARN rm not removing /home/daniel/Projects/JavaScript/amazon-music-linux/node_modules/.bin/electron-download as it wasn't installed by /home/daniel/Projects/JavaScript/amazon-music-linux/node_modules/electron-download
npm WARN rm not removing /home/daniel/Projects/JavaScript/amazon-music-linux/node_modules/.bin/uglifyjs as it wasn't installed by /home/daniel/Projects/JavaScript/amazon-music-linux/node_modules/uglify-js
npm WARN rm not removing /home/daniel/Projects/JavaScript/amazon-music-linux/node_modules/.bin/mkdirp as it wasn't installed by /home/daniel/Projects/JavaScript/amazon-music-linux/node_modules/mkdirp
npm WARN rm not removing /home/daniel/Projects/JavaScript/amazon-music-linux/node_modules/.bin/mime as it wasn't installed by /home/daniel/Projects/JavaScript/amazon-music-linux/node_modules/mime
npm WARN rm not removing /home/daniel/Projects/JavaScript/amazon-music-linux/node_modules/.bin/browserslist as it wasn't installed by /home/daniel/Projects/JavaScript/amazon-music-linux/node_modules/browserslist

> segfault-handler@1.0.0 install /home/daniel/Projects/JavaScript/amazon-music-linux/node_modules/segfault-handler
> node-gyp rebuild

make: Verzeichnis „/home/daniel/Projects/JavaScript/amazon-music-linux/node_modules/segfault-handler/build“ wird betreten
  CXX(target) Release/obj.target/segfault-handler/src/segfault-handler.o
../src/segfault-handler.cpp:8:10: schwerwiegender Fehler: v8-debug.h: Datei oder Verzeichnis nicht gefunden
 #include <v8-debug.h>
          ^~~~~~~~~~~~
Kompilierung beendet.
make: *** [segfault-handler.target.mk:97: Release/obj.target/segfault-handler/src/segfault-handler.o] Fehler 1
make: Verzeichnis „/home/daniel/Projects/JavaScript/amazon-music-linux/node_modules/segfault-handler/build“ wird verlassen
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:225:12)
gyp ERR! System Linux 4.14.39-1-MANJARO
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/daniel/Projects/JavaScript/amazon-music-linux/node_modules/segfault-handler
gyp ERR! node -v v10.0.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm WARN amazon-music-linux@0.1.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-win@2.2.0 (node_modules/7zip-bin-win):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-win@2.2.0: wanted {"os":"win32","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: app-builder-bin-mac@1.8.6 (node_modules/app-builder-bin-mac):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for app-builder-bin-mac@1.8.6: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: app-builder-bin-win@1.8.6 (node_modules/app-builder-bin-win):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for app-builder-bin-win@1.8.6: wanted {"os":"win32","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-mac@1.0.1 (node_modules/7zip-bin-mac):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-mac@1.0.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! segfault-handler@1.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the segfault-handler@1.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/daniel/.npm/_logs/2018-05-14T16_59_24_971Z-debug.log
```

**Comment by Djiit** [comment]
Hi there, thanks for your feedback. Currently iohook is not compatible with Node.js 10. (see https://github.com/ddopson/node-segfault-handler/pull/50). Could you test with Node 9 ?

**Comment by danieldaeschle** [comment]
I will try to install LTS version on Manjaro. Thanks for your answer.

**Comment by danieldaeschle** [comment]
Installed NVM, then installed Version 8.6.x of Node and it worked!
