### ISSUE TITLE
Won't install on OSX 10.11.6 | node 7.1.0

### ISSUE THREAD

**Issue by gabrielstuff** [WilixLead/iohook#9]
Hello,

I'm really happy to discovered this module. It looks great !
Unfortunately, while trying to install it, here is what I get: 

```
> $ npm install iohook --save                                                   ⬡ 7.1.0

> iohook@0.1.2 install /Users/gabrielstuff/Sources/node/soixante/playground/mouse/node_modules/iohook
> node ./install install

Try use default
Recompiling iohook for your environment
Platform is: iohook_darwin_x64
fatal: Not a git repository (or any of the parent directories): .git
child_process.js:531
    throw err;
    ^

Error: Command failed: git submodule update --init
fatal: Not a git repository (or any of the parent directories): .git

    at checkExecSyncError (child_process.js:488:13)
    at Object.execSync (child_process.js:528:13)
    at Object.<anonymous> (/Users/gabrielstuff/Sources/node/soixante/playground/mouse/node_modules/iohook/install.js:24:10)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.runMain (module.js:607:10)
    at run (bootstrap_node.js:420:7)
npm WARN mouse@1.0.0 No description
npm WARN mouse@1.0.0 No repository field.
npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/gabrielstuff/.nvm/versions/node/v7.1.0/bin/node" "/Users/gabrielstuff/.nvm/versions/node/v7.1.0/bin/npm" "install" "iohook" "--save"
npm ERR! node v7.1.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE

npm ERR! iohook@0.1.2 install: `node ./install install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the iohook@0.1.2 install script 'node ./install install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the iohook package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./install install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs iohook
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls iohook
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
```

Log file bellow:

```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/gabrielstuff/.nvm/versions/node/v7.1.0/bin/node',
1 verbose cli   '/Users/gabrielstuff/.nvm/versions/node/v7.1.0/bin/npm',
1 verbose cli   'install',
1 verbose cli   'iohook',
1 verbose cli   '--save' ]
2 info using npm@3.10.9
3 info using node@v7.1.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData iohook
8 silly fetchNamedPackageData iohook
9 silly mapToRegistry name iohook
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'iohook',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'iohook',
12 silly mapToRegistry   name: 'iohook',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/iohook
14 verbose request uri https://registry.npmjs.org/iohook
15 verbose request no auth needed
16 info attempt registry request try #1 at 6:25:25 AM
17 verbose request using bearer token for auth
18 verbose request id fcbcaac16ad5773b
19 verbose etag W/"58d68bbf-4d8a"
20 verbose lastModified Sat, 25 Mar 2017 15:24:47 GMT
21 http request GET https://registry.npmjs.org/iohook
22 http 304 https://registry.npmjs.org/iohook
23 verbose headers { server: 'nginx/1.10.1',
23 verbose headers   'last-modified': 'Sat, 25 Mar 2017 15:24:47 GMT',
23 verbose headers   etag: '"58d68bbf-4d8a"',
23 verbose headers   'cache-control': 'max-age=300',
23 verbose headers   'accept-ranges': 'bytes',
23 verbose headers   date: 'Tue, 28 Mar 2017 22:25:26 GMT',
23 verbose headers   via: '1.1 varnish',
23 verbose headers   connection: 'keep-alive',
23 verbose headers   'x-served-by': 'cache-nrt6131-NRT',
23 verbose headers   'x-cache': 'MISS',
23 verbose headers   'x-cache-hits': '0',
23 verbose headers   'x-timer': 'S1490739926.297512,VS0,VE147',
23 verbose headers   vary: 'Accept-Encoding' }
24 silly get cb [ 304,
24 silly get   { server: 'nginx/1.10.1',
24 silly get     'last-modified': 'Sat, 25 Mar 2017 15:24:47 GMT',
24 silly get     etag: '"58d68bbf-4d8a"',
24 silly get     'cache-control': 'max-age=300',
24 silly get     'accept-ranges': 'bytes',
24 silly get     date: 'Tue, 28 Mar 2017 22:25:26 GMT',
24 silly get     via: '1.1 varnish',
24 silly get     connection: 'keep-alive',
24 silly get     'x-served-by': 'cache-nrt6131-NRT',
24 silly get     'x-cache': 'MISS',
24 silly get     'x-cache-hits': '0',
24 silly get     'x-timer': 'S1490739926.297512,VS0,VE147',
24 silly get     vary: 'Accept-Encoding' } ]
25 verbose etag https://registry.npmjs.org/iohook from cache
26 verbose get saving iohook to /Users/gabrielstuff/.npm/registry.npmjs.org/iohook/.cache.json
27 verbose correctMkdir /Users/gabrielstuff/.npm correctMkdir not in flight; initializing
28 silly install normalizeTree
29 silly loadCurrentTree Finishing
30 silly loadIdealTree Starting
31 silly install loadIdealTree
32 silly cloneCurrentTree Starting
33 silly install cloneCurrentTreeToIdealTree
34 silly cloneCurrentTree Finishing
35 silly loadShrinkwrap Starting
36 silly install loadShrinkwrap
37 silly loadShrinkwrap Finishing
38 silly loadAllDepsIntoIdealTree Starting
39 silly install loadAllDepsIntoIdealTree
40 silly resolveWithNewModule iohook@0.1.2 checking installable status
41 silly cache add args [ 'iohook', null ]
42 verbose cache add spec iohook
43 silly cache add parsed spec Result {
43 silly cache add   raw: 'iohook',
43 silly cache add   scope: null,
43 silly cache add   escapedName: 'iohook',
43 silly cache add   name: 'iohook',
43 silly cache add   rawSpec: '',
43 silly cache add   spec: 'latest',
43 silly cache add   type: 'tag' }
44 silly addNamed iohook@latest
45 verbose addNamed "latest" is being treated as a dist-tag for iohook
46 info addNameTag [ 'iohook', 'latest' ]
47 silly mapToRegistry name iohook
48 silly mapToRegistry using default registry
49 silly mapToRegistry registry https://registry.npmjs.org/
50 silly mapToRegistry data Result {
50 silly mapToRegistry   raw: 'iohook',
50 silly mapToRegistry   scope: null,
50 silly mapToRegistry   escapedName: 'iohook',
50 silly mapToRegistry   name: 'iohook',
50 silly mapToRegistry   rawSpec: '',
50 silly mapToRegistry   spec: 'latest',
50 silly mapToRegistry   type: 'tag' }
51 silly mapToRegistry uri https://registry.npmjs.org/iohook
52 verbose addNameTag registry:https://registry.npmjs.org/iohook not in flight; fetching
53 verbose get https://registry.npmjs.org/iohook not expired, no request
54 silly addNameTag next cb for iohook with tag latest
55 silly addNamed iohook@0.1.2
56 verbose addNamed "0.1.2" is a plain semver version for iohook
57 silly cache afterAdd iohook@0.1.2
58 verbose afterAdd /Users/gabrielstuff/.npm/iohook/0.1.2/package/package.json not in flight; writing
59 verbose correctMkdir /Users/gabrielstuff/.npm correctMkdir not in flight; initializing
60 verbose afterAdd /Users/gabrielstuff/.npm/iohook/0.1.2/package/package.json written
61 silly fetchNamedPackageData bindings
62 silly mapToRegistry name bindings
63 silly mapToRegistry using default registry
64 silly mapToRegistry registry https://registry.npmjs.org/
65 silly mapToRegistry data Result {
65 silly mapToRegistry   raw: 'bindings',
65 silly mapToRegistry   scope: null,
65 silly mapToRegistry   escapedName: 'bindings',
65 silly mapToRegistry   name: 'bindings',
65 silly mapToRegistry   rawSpec: '',
65 silly mapToRegistry   spec: 'latest',
65 silly mapToRegistry   type: 'tag' }
66 silly mapToRegistry uri https://registry.npmjs.org/bindings
67 verbose request uri https://registry.npmjs.org/bindings
68 verbose request no auth needed
69 info attempt registry request try #1 at 6:25:26 AM
70 verbose request using bearer token for auth
71 verbose etag W/"580645d3-46f7"
72 verbose lastModified Tue, 18 Oct 2016 15:54:59 GMT
73 http request GET https://registry.npmjs.org/bindings
74 http 304 https://registry.npmjs.org/bindings
75 verbose headers { server: 'nginx/1.10.1',
75 verbose headers   'last-modified': 'Tue, 18 Oct 2016 15:54:59 GMT',
75 verbose headers   etag: '"580645d3-46f7"',
75 verbose headers   'cache-control': 'max-age=300',
75 verbose headers   'accept-ranges': 'bytes',
75 verbose headers   date: 'Tue, 28 Mar 2017 22:25:26 GMT',
75 verbose headers   via: '1.1 varnish',
75 verbose headers   connection: 'keep-alive',
75 verbose headers   'x-served-by': 'cache-nrt6131-NRT',
75 verbose headers   'x-cache': 'MISS',
75 verbose headers   'x-cache-hits': '0',
75 verbose headers   'x-timer': 'S1490739926.663469,VS0,VE172',
75 verbose headers   vary: 'Accept-Encoding' }
76 silly get cb [ 304,
76 silly get   { server: 'nginx/1.10.1',
76 silly get     'last-modified': 'Tue, 18 Oct 2016 15:54:59 GMT',
76 silly get     etag: '"580645d3-46f7"',
76 silly get     'cache-control': 'max-age=300',
76 silly get     'accept-ranges': 'bytes',
76 silly get     date: 'Tue, 28 Mar 2017 22:25:26 GMT',
76 silly get     via: '1.1 varnish',
76 silly get     connection: 'keep-alive',
76 silly get     'x-served-by': 'cache-nrt6131-NRT',
76 silly get     'x-cache': 'MISS',
76 silly get     'x-cache-hits': '0',
76 silly get     'x-timer': 'S1490739926.663469,VS0,VE172',
76 silly get     vary: 'Accept-Encoding' } ]
77 verbose etag https://registry.npmjs.org/bindings from cache
78 verbose get saving bindings to /Users/gabrielstuff/.npm/registry.npmjs.org/bindings/.cache.json
79 verbose correctMkdir /Users/gabrielstuff/.npm correctMkdir not in flight; initializing
80 silly resolveWithNewModule bindings@1.2.1 checking installable status
81 silly cache add args [ 'bindings@^1.2.1', null ]
82 verbose cache add spec bindings@^1.2.1
83 silly cache add parsed spec Result {
83 silly cache add   raw: 'bindings@^1.2.1',
83 silly cache add   scope: null,
83 silly cache add   escapedName: 'bindings',
83 silly cache add   name: 'bindings',
83 silly cache add   rawSpec: '^1.2.1',
83 silly cache add   spec: '>=1.2.1 <2.0.0',
83 silly cache add   type: 'range' }
84 silly addNamed bindings@>=1.2.1 <2.0.0
85 verbose addNamed ">=1.2.1 <2.0.0" is a valid semver range for bindings
86 silly addNameRange { name: 'bindings', range: '>=1.2.1 <2.0.0', hasData: false }
87 silly mapToRegistry name bindings
88 silly mapToRegistry using default registry
89 silly mapToRegistry registry https://registry.npmjs.org/
90 silly mapToRegistry data Result {
90 silly mapToRegistry   raw: 'bindings',
90 silly mapToRegistry   scope: null,
90 silly mapToRegistry   escapedName: 'bindings',
90 silly mapToRegistry   name: 'bindings',
90 silly mapToRegistry   rawSpec: '',
90 silly mapToRegistry   spec: 'latest',
90 silly mapToRegistry   type: 'tag' }
91 silly mapToRegistry uri https://registry.npmjs.org/bindings
92 verbose addNameRange registry:https://registry.npmjs.org/bindings not in flight; fetching
93 verbose get https://registry.npmjs.org/bindings not expired, no request
94 silly addNameRange number 2 { name: 'bindings', range: '>=1.2.1 <2.0.0', hasData: true }
95 silly addNameRange versions [ 'bindings',
95 silly addNameRange   [ '0.0.1',
95 silly addNameRange     '0.1.0',
95 silly addNameRange     '0.1.1',
95 silly addNameRange     '0.2.0',
95 silly addNameRange     '0.2.1',
95 silly addNameRange     '0.2.2',
95 silly addNameRange     '0.2.3',
95 silly addNameRange     '0.2.4',
95 silly addNameRange     '0.3.0',
95 silly addNameRange     '0.4.0',
95 silly addNameRange     '1.0.0',
95 silly addNameRange     '1.1.0',
95 silly addNameRange     '1.1.1',
95 silly addNameRange     '1.2.0',
95 silly addNameRange     '1.2.1' ] ]
96 silly addNamed bindings@1.2.1
97 verbose addNamed "1.2.1" is a plain semver version for bindings
98 silly cache afterAdd bindings@1.2.1
99 verbose afterAdd /Users/gabrielstuff/.npm/bindings/1.2.1/package/package.json not in flight; writing
100 verbose correctMkdir /Users/gabrielstuff/.npm correctMkdir not in flight; initializing
101 verbose afterAdd /Users/gabrielstuff/.npm/bindings/1.2.1/package/package.json written
102 silly loadAllDepsIntoIdealTree Finishing
103 silly loadIdealTree Finishing
104 silly currentTree mouse@1.0.0
104 silly currentTree └── node-mouse@0.0.2
105 silly idealTree mouse@1.0.0
105 silly idealTree ├── bindings@1.2.1
105 silly idealTree ├── iohook@0.1.2
105 silly idealTree └── node-mouse@0.0.2
106 silly generateActionsToTake Starting
107 silly install generateActionsToTake
108 silly generateActionsToTake Finishing
109 silly diffTrees action count 2
110 silly diffTrees add bindings@1.2.1
111 silly diffTrees add iohook@0.1.2
112 silly decomposeActions action count 16
113 silly decomposeActions fetch bindings@1.2.1
114 silly decomposeActions extract bindings@1.2.1
115 silly decomposeActions test bindings@1.2.1
116 silly decomposeActions preinstall bindings@1.2.1
117 silly decomposeActions build bindings@1.2.1
118 silly decomposeActions install bindings@1.2.1
119 silly decomposeActions postinstall bindings@1.2.1
120 silly decomposeActions finalize bindings@1.2.1
121 silly decomposeActions fetch iohook@0.1.2
122 silly decomposeActions extract iohook@0.1.2
123 silly decomposeActions test iohook@0.1.2
124 silly decomposeActions preinstall iohook@0.1.2
125 silly decomposeActions build iohook@0.1.2
126 silly decomposeActions install iohook@0.1.2
127 silly decomposeActions postinstall iohook@0.1.2
128 silly decomposeActions finalize iohook@0.1.2
129 silly runTopLevelLifecycles Starting
130 silly executeActions Starting
131 silly install executeActions
132 silly doSerial global-install 0
133 silly doParallel fetch 2
134 verbose correctMkdir /Users/gabrielstuff/.npm/_locks correctMkdir not in flight; initializing
135 verbose lock using /Users/gabrielstuff/.npm/_locks/staging-0303ebea3bd89d5c.lock for /Users/gabrielstuff/Sources/node/soixante/playground/mouse/node_modules/.staging
136 silly doParallel extract 2
137 silly extract bindings@1.2.1
138 silly extract iohook@0.1.2
139 verbose unbuild node_modules/.staging/bindings-00db33d4
140 verbose unbuild node_modules/.staging/iohook-198f6a4b
141 silly gentlyRm /Users/gabrielstuff/Sources/node/soixante/playground/mouse/node_modules/.staging/bindings-00db33d4 is being purged from base /Users/gabrielstuff/Sources/node/soixante/playground/mouse
142 verbose gentlyRm don't care about contents; nuking /Users/gabrielstuff/Sources/node/soixante/playground/mouse/node_modules/.staging/bindings-00db33d4
143 verbose tar unpack /Users/gabrielstuff/.npm/bindings/1.2.1/package.tgz
144 verbose tar unpacking to /Users/gabrielstuff/Sources/node/soixante/playground/mouse/node_modules/.staging/bindings-00db33d4
145 silly gentlyRm /Users/gabrielstuff/Sources/node/soixante/playground/mouse/node_modules/.staging/bindings-00db33d4 is being purged
146 verbose gentlyRm don't care about contents; nuking /Users/gabrielstuff/Sources/node/soixante/playground/mouse/node_modules/.staging/bindings-00db33d4
147 silly gunzTarPerm modes [ '755', '644' ]
148 silly gentlyRm /Users/gabrielstuff/Sources/node/soixante/playground/mouse/node_modules/.staging/iohook-198f6a4b is being purged from base /Users/gabrielstuff/Sources/node/soixante/playground/mouse
149 verbose gentlyRm don't care about contents; nuking /Users/gabrielstuff/Sources/node/soixante/playground/mouse/node_modules/.staging/iohook-198f6a4b
150 verbose tar unpack /Users/gabrielstuff/.npm/iohook/0.1.2/package.tgz
151 verbose tar unpacking to /Users/gabrielstuff/Sources/node/soixante/playground/mouse/node_modules/.staging/iohook-198f6a4b
152 silly gentlyRm /Users/gabrielstuff/Sources/node/soixante/playground/mouse/node_modules/.staging/iohook-198f6a4b is being purged
153 verbose gentlyRm don't care about contents; nuking /Users/gabrielstuff/Sources/node/soixante/playground/mouse/node_modules/.staging/iohook-198f6a4b
154 silly gunzTarPerm modes [ '755', '644' ]
155 silly gunzTarPerm extractEntry package.json
156 silly gunzTarPerm extractEntry package.json
157 silly gunzTarPerm extractEntry README.md
158 silly gunzTarPerm extractEntry bindings.js
159 silly gunzTarPerm extractEntry .npmignore
160 silly gunzTarPerm extractEntry README.md
161 silly gunzTarPerm extractEntry LICENSE
162 silly gunzTarPerm extractEntry example.js
163 silly gunzTarPerm extractEntry index.js
164 silly gunzTarPerm extractEntry install.js
165 silly gunzTarPerm extractEntry eletron-example/package.json
166 silly gunzTarPerm extractEntry eletron-example/README.md
167 silly gunzTarPerm extractEntry eletron-example/main.js
168 silly gunzTarPerm extractEntry CMakeLists.txt
169 silly gunzTarPerm extractEntry .gitmodules
170 silly gunzTarPerm extractEntry src/iohook.cc
171 silly gunzTarPerm extractEntry src/iohook.h
172 silly gentlyRm /Users/gabrielstuff/Sources/node/soixante/playground/mouse/node_modules/.staging/bindings-00db33d4/node_modules is being purged
173 verbose gentlyRm don't care about contents; nuking /Users/gabrielstuff/Sources/node/soixante/playground/mouse/node_modules/.staging/bindings-00db33d4/node_modules
174 silly gentlyRm /Users/gabrielstuff/Sources/node/soixante/playground/mouse/node_modules/.staging/iohook-198f6a4b/node_modules is being purged
175 verbose gentlyRm don't care about contents; nuking /Users/gabrielstuff/Sources/node/soixante/playground/mouse/node_modules/.staging/iohook-198f6a4b/node_modules
176 silly doParallel preinstall 2
177 silly preinstall bindings@1.2.1 /Users/gabrielstuff/Sources/node/soixante/playground/mouse/node_modules/.staging/bindings-00db33d4
178 info lifecycle bindings@1.2.1~preinstall: bindings@1.2.1
179 silly preinstall iohook@0.1.2 /Users/gabrielstuff/Sources/node/soixante/playground/mouse/node_modules/.staging/iohook-198f6a4b
180 info lifecycle iohook@0.1.2~preinstall: iohook@0.1.2
181 silly lifecycle bindings@1.2.1~preinstall: no script for preinstall, continuing
182 silly lifecycle iohook@0.1.2~preinstall: no script for preinstall, continuing
183 silly doReverseSerial remove 0
184 silly doSerial move 0
185 silly doSerial finalize 2
186 silly finalize /Users/gabrielstuff/Sources/node/soixante/playground/mouse/node_modules/bindings
187 silly finalize /Users/gabrielstuff/Sources/node/soixante/playground/mouse/node_modules/iohook
188 silly doSerial build 2
189 silly build bindings@1.2.1
190 info linkStuff bindings@1.2.1
191 silly linkStuff bindings@1.2.1 has /Users/gabrielstuff/Sources/node/soixante/playground/mouse/node_modules as its parent node_modules
192 verbose linkBins bindings@1.2.1
193 verbose linkMans bindings@1.2.1
194 silly build iohook@0.1.2
195 info linkStuff iohook@0.1.2
196 silly linkStuff iohook@0.1.2 has /Users/gabrielstuff/Sources/node/soixante/playground/mouse/node_modules as its parent node_modules
197 verbose linkBins iohook@0.1.2
198 verbose linkMans iohook@0.1.2
199 silly doSerial global-link 0
200 silly doParallel update-linked 0
201 silly doSerial install 2
202 silly install bindings@1.2.1 /Users/gabrielstuff/Sources/node/soixante/playground/mouse/node_modules/.staging/bindings-00db33d4
203 info lifecycle bindings@1.2.1~install: bindings@1.2.1
204 silly lifecycle bindings@1.2.1~install: no script for install, continuing
205 silly install iohook@0.1.2 /Users/gabrielstuff/Sources/node/soixante/playground/mouse/node_modules/.staging/iohook-198f6a4b
206 info lifecycle iohook@0.1.2~install: iohook@0.1.2
207 verbose lifecycle iohook@0.1.2~install: unsafe-perm in lifecycle true
208 verbose lifecycle iohook@0.1.2~install: PATH: /Users/gabrielstuff/.nvm/versions/node/v7.1.0/lib/node_modules/npm/bin/node-gyp-bin:/Users/gabrielstuff/Sources/node/soixante/playground/mouse/node_modules/iohook/node_modules/.bin:/Users/gabrielstuff/Sources/node/soixante/playground/mouse/node_modules/.bin:/Users/gabrielstuff/.nvm/versions/node/v7.1.0/bin:/Users/gabrielstuff/.avn/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Users/gabrielstuff/.rvm/bin:/Users/gabrielstuff/.composer/vendor/bin/
209 verbose lifecycle iohook@0.1.2~install: CWD: /Users/gabrielstuff/Sources/node/soixante/playground/mouse/node_modules/iohook
210 silly lifecycle iohook@0.1.2~install: Args: [ '-c', 'node ./install install' ]
211 silly lifecycle iohook@0.1.2~install: Returned: code: 1  signal: null
212 info lifecycle iohook@0.1.2~install: Failed to exec install script
213 verbose unlock done using /Users/gabrielstuff/.npm/_locks/staging-0303ebea3bd89d5c.lock for /Users/gabrielstuff/Sources/node/soixante/playground/mouse/node_modules/.staging
214 silly rollbackFailedOptional Starting
215 silly rollbackFailedOptional Finishing
216 silly runTopLevelLifecycles Finishing
217 silly install printInstalled
218 warn mouse@1.0.0 No description
219 verbose If you need help, you may report this error at:
219 verbose     <https://github.com/npm/npm/issues>
220 warn mouse@1.0.0 No repository field.
221 verbose If you need help, you may report this error at:
221 verbose     <https://github.com/npm/npm/issues>
222 verbose stack Error: iohook@0.1.2 install: `node ./install install`
222 verbose stack Exit status 1
222 verbose stack     at EventEmitter.<anonymous> (/Users/gabrielstuff/.nvm/versions/node/v7.1.0/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
222 verbose stack     at emitTwo (events.js:106:13)
222 verbose stack     at EventEmitter.emit (events.js:191:7)
222 verbose stack     at ChildProcess.<anonymous> (/Users/gabrielstuff/.nvm/versions/node/v7.1.0/lib/node_modules/npm/lib/utils/spawn.js:40:14)
222 verbose stack     at emitTwo (events.js:106:13)
222 verbose stack     at ChildProcess.emit (events.js:191:7)
222 verbose stack     at maybeClose (internal/child_process.js:885:16)
222 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
223 verbose pkgid iohook@0.1.2
224 verbose cwd /Users/gabrielstuff/Sources/node/soixante/playground/mouse
225 error Darwin 15.6.0
226 error argv "/Users/gabrielstuff/.nvm/versions/node/v7.1.0/bin/node" "/Users/gabrielstuff/.nvm/versions/node/v7.1.0/bin/npm" "install" "iohook" "--save"
227 error node v7.1.0
228 error npm  v3.10.9
229 error code ELIFECYCLE
230 error iohook@0.1.2 install: `node ./install install`
230 error Exit status 1
231 error Failed at the iohook@0.1.2 install script 'node ./install install'.
231 error Make sure you have the latest version of node.js and npm installed.
231 error If you do, this is most likely a problem with the iohook package,
231 error not with npm itself.
231 error Tell the author that this fails on your system:
231 error     node ./install install
231 error You can get information on how to open an issue for this project with:
231 error     npm bugs iohook
231 error Or if that isn't available, you can get their info via:
231 error     npm owner ls iohook
231 error There is likely additional logging output above.
232 verbose exit [ 1, true ]
```

**Comment by gabrielstuff** [comment]
If I clone the repo and run: `npm i` or `yarn` it goes well and I can run the example and I'm happy. So this certainly have to do with the pre-packaged version.

**Comment by WilixLead** [comment]
Try to use new version with prebuilds

**Comment by gabrielstuff** [comment]
Using node 7.4.0 and a fresh install. I got : 

```
Loading native binary: ./builds/node-v51-darwin-x64/build/Release/iohook.node
module.js:472
    throw err;
    ^

Error: Cannot find module './builds/node-v51-darwin-x64/build/Release/iohook.node'
```

no `builds` folder exist.

**Comment by WilixLead** [comment]
Please provide installation log

**Comment by gabrielstuff** [comment]
Hi @WilixLead,

here are the logs, with yarn:

https://gist.github.com/anonymous/a91af020a0cc162107e1ffb022a59155

with npm:

https://gist.github.com/anonymous/c9e037883fd55568578172aad147b5d6

Also, note that last version won't compile. The previous one used to work nicely.
